#index:
#    path: /
#    controller: App\Controller\DefaultController::index

bureau:
      path: /bureau
      controller: App\Controller\MembreController:show

assemblee_generale:
      path: /assemblee-generale
      controller: App\Controller\AssembleeGeneraleController:index

